// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PizzaData;

namespace PizzaData.Migrations
{
    [DbContext(typeof(PizzaContext))]
    partial class PizzaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("PizzaData.Models.Ingredient", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Cost");

                    b.Property<string>("Description");

                    b.HasKey("Name");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("PizzaData.Models.Pizza", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Cost");

                    b.Property<string>("Description");

                    b.Property<string>("IngredientName");

                    b.Property<string>("PizzaName");

                    b.HasKey("Name");

                    b.HasIndex("IngredientName");

                    b.HasIndex("PizzaName");

                    b.ToTable("Pizza");
                });

            modelBuilder.Entity("PizzaData.Models.Pizza", b =>
                {
                    b.HasOne("PizzaData.Models.Ingredient")
                        .WithMany("Pizzas")
                        .HasForeignKey("IngredientName");

                    b.HasOne("PizzaData.Models.Pizza")
                        .WithMany("Recipe")
                        .HasForeignKey("PizzaName");
                });
#pragma warning restore 612, 618
        }
    }
}
